---
knit: (function(input_file, encoding) {
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), 'index.html'))})
output: 
  html_document:
    theme: null
    highlight: null
    css: styles.css
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.align = 'center',
                      echo=FALSE, warning=FALSE, message=FALSE)
library(tidyverse)
library(patchwork)
library(tidybayes)
library(lubridate)
library(htmltab)
library(brms)
library(here)
library(glue)
library("stringr")
library("googledrive")
library("rio")
library("readxl")
library("hrbrthemes")
library("sjlabelled")
library("seatdist")
library("rgdal")
library("maptools") 
library("rgeos") 
library("gpclib")
```

```{r echo = F, eval = T, include=F}
load("~/Desktop/PoolingthePoles.RData")
names <- data.frame(as.factor(get_labels(polls$org)))
names <- separate(names, as.factor.get_labels.polls.org.., c("house", "method"), sep=",")
names$house <- as.factor(names$house)
housenames <- fct_recode(names$house, "Kantar" = "Kantar") %>%
  fct_collapse(., Kantar=c("Kantar"))
#names <- paste0(get_labels(housenames), collapse=", ")
names <- glue_collapse(get_labels(housenames), ", ", last = " and ")
polls$org <- str_replace_all(polls$org, "_", ", ")
```

# Pooling the Poles

```{r, echo=F, results='asis'}
cat("Pooled polls of intended voting at parliamentary elections in Poland, ", gsub(" 0", " ", format(Sys.time(), '%A %d %B')),".", sep="")
```

```{r, echo=F, results='asis'}
cat(str_c("Data from ", names, "."))
```

```{r, echo=F, results='asis'}
plotdraws <- add_fitted_draws(
  model = m1,
  newdata =
    tibble(time = today),
  re_formula = NA
) %>%
  group_by(.category) %>%
  mutate(.category = factor(.category,
                            levels = c("PiS", "KO", "Lewica", "Konfederacja", "Other", "PSL", "Polska2050"),
                            labels = c("PiS", "KO", "Lewica", "Konfederacja", "Other", "PSL","Polska 2050")))

medians <- plotdraws %>%
  summarise(est = median(.value)*100, .groups = "drop")

PiS.KO.diff <- plotdraws %>%
  pivot_wider(names_from=.category, values_from=.value) %>%
  mutate(., PiSKO = PiS-KO,
         PiSKO = sum((PiSKO > 0) / length(PiSKO)),
         PiSKO = round(PiSKO, 2)) %>%
  pull(PiSKO) %>%
  last(.)

KO.P50.diff <- plotdraws %>%
  pivot_wider(names_from=.category, values_from=.value) %>%
  mutate(., KOP50 = KO-`Polska 2050`,
         KOP50 = sum((KOP50 > 0) / length(KOP50)),
         KOP50 = round(KOP50, 2)) %>%
  pull(KOP50) %>%
  last(.)

P50.Lewica.diff <- plotdraws %>%
  pivot_wider(names_from=.category, values_from=.value) %>%
  mutate(., P50Lew = `Polska 2050`-Lewica,
         P50Lew = sum((P50Lew > 0) / length(P50Lew)),
         P50Lew = round(P50Lew, 2)) %>%
  pull(P50Lew) %>%
  last(.)

Lewica_5 <- plotdraws %>%
  pivot_wider(names_from=.category, values_from=.value) %>%
  mutate(., Lewica_5 = Lewica-0.05,
         Lewica_5 = sum((Lewica_5 > 0) / length(Lewica_5)),
         Lewica_5 = round(Lewica_5, 2)) %>%
  pull(Lewica_5) %>%
  last(.)

PSL_5 <- plotdraws %>%
  pivot_wider(names_from=.category, values_from=.value) %>%
  mutate(., PSL_5 = PSL-0.05,
         PSL_5 = sum((PSL_5 > 0) / length(PSL_5)),
         PSL_5 = round(PSL_5, 2)) %>%
  pull(PSL_5) %>%
  last(.)

Konfederacja_5 <- plotdraws %>%
  pivot_wider(names_from=.category, values_from=.value) %>%
  mutate(., Konfederacja_5 = Konfederacja-0.05,
         Konfederacja_5 = sum((Konfederacja_5 > 0) / length(Konfederacja_5)),
         Konfederacja_5 = round(Konfederacja_5, 2)) %>%
  pull(Konfederacja_5) %>%
  last(.)
```

## Latest estimates

```{r, fig.align='center'}
add_fitted_draws(
    model = m1,
    newdata =
      tibble(time = today),
    re_formula = NA
  ) %>%
  group_by(.category) %>%
  mutate(.category = factor(.category,
    levels = c("PiS", "KO", "Lewica", "Konfederacja", "Other", "PSL", "Polska2050"),
    labels = c("PiS", "KO", "Lewica", "Konfederacja", "Other", "PSL", "Polska 2050"))) %>%
  ggplot() +
  geom_vline(aes(xintercept=0.05), colour="gray40", linetype="dotted") +
  stat_slab(aes(y=reorder(.category, dplyr::desc(-.value)), 
                 x=.value, fill=.category), normalize="xy") +
  scale_y_discrete(name="", position="right") +
  annotate(geom = "text", label=paste(round(medians$est[medians$.category=="PiS"],0)),
           y="PiS", x=medians$est[medians$.category=="PiS"]/100, size=4, hjust = "center", vjust=-1,
           family="Roboto Condensed", color="white") +
  annotate(geom = "text", label=paste(round(medians$est[medians$.category=="KO"],0)),
           y="KO", x=medians$est[medians$.category=="KO"]/100, size=4, hjust = "center", vjust=-1,
           family="Roboto Condensed", color="white") +
  annotate(geom = "text", label=paste(round(medians$est[medians$.category=="Polska 2050"],0)),
           y="Polska 2050", x=medians$est[medians$.category=="Polska 2050"]/100, size=4, hjust = "center", vjust=-1,
           family="Roboto Condensed", color="white") +
  annotate(geom = "text", label=paste(round(medians$est[medians$.category=="Lewica"],0)),
           y="Lewica", x=medians$est[medians$.category=="Lewica"]/100, size=4, hjust = "center", vjust=-1,
           family="Roboto Condensed", color="white") +
  annotate(geom = "text", label=paste(round(medians$est[medians$.category=="Konfederacja"],0)),
           y="Konfederacja", x=medians$est[medians$.category=="Konfederacja"]/100, size=4, hjust = "center", vjust=-1,
           family="Roboto Condensed", color="white") +
  annotate(geom = "text", label=paste(round(medians$est[medians$.category=="PSL"],0)),
           y="PSL", x=medians$est[medians$.category=="PSL"]/100, size=4, hjust = "center", vjust=-1,
           family="Roboto Condensed", color="white") +
  annotate(geom = "text", label=paste(round(medians$est[medians$.category=="Other"],0)),
           y="Other", x=medians$est[medians$.category=="Other"]/100, size=4, hjust = "center", vjust=-1,
           family="Roboto Condensed", color="white") +
  annotate(geom = "text", label=paste("Pr(PiS > KO)  = ", PiS.KO.diff), y="PiS",
           x=quantile(plotdraws$.value[plotdraws$.category=="PiS"], 0.005), size=3.5, adj=c(1), vjust=-3, family="Roboto Condensed Light") +
  annotate(geom = "text", label=paste("Pr(KO > Polska 2050)  = ", KO.P50.diff), y="KO",
           x=quantile(plotdraws$.value[plotdraws$.category=="KO"], 0.005), size=3.5, adj=c(1), vjust=-3, family="Roboto Condensed Light") +
  annotate(geom = "text", label=paste("Pr(Lewica > 5%)  = ", Lewica_5), y="Lewica",
           x=quantile(plotdraws$.value[plotdraws$.category=="Lewica"], 0.999), size=3.5, adj=c(0), vjust=-4, family="Roboto Condensed Light") +
  annotate(geom = "text", label=paste("Pr(PSL > 5%)  = ", PSL_5), y="PSL",
           x=quantile(plotdraws$.value[plotdraws$.category=="PSL"], 0.999), size=3.5, adj=c(0), vjust=-4, family="Roboto Condensed Light") +
  annotate(geom = "text", label=paste("Pr(Konfederacja > 5%)  = ", Konfederacja_5), y="Konfederacja",
           x=quantile(plotdraws$.value[plotdraws$.category=="Konfederacja"], 0.999), size=3.5, adj=c(0), vjust=-4, family="Roboto Condensed Light") +
  scale_fill_manual(name=" ", values=cols, guide=FALSE) +
  scale_x_continuous(breaks=c(0, 0.5, 0.8, 0.1, 0.2, 0.3, 0.4, 0.5), labels=c("0", "5", "8", "10", "20", "30", "40", "50")) +
  expand_limits(x = 0) +
  labs(x="") +
  theme_minimal() +
  theme_ipsum_rc() +
  theme_changes 
```

## Trends

```{r, fig.align='center'}
today <- interval(min(polls$midDate), Sys.Date())/years(1)

pred_dta <-
  tibble(
    time = seq(0, today, length.out = nrow(polls)),
    date = as.Date(time*365, origin = min(polls$midDate))
  )

pred_dta <-
  add_fitted_draws(
    model = m1,
    newdata = pred_dta,
    re_formula = NA
  ) %>%
  group_by(date, .category) %>%
  rename(party = .category) %>%
  mutate(
    party =
      party %>%
      factor(
        levels = c("PiS", "KO", "Polska2050", "Lewica", "Konfederacja", "PSL", "Other"),
        labels = c("PiS", "KO", "Polska 2050", "Lewica", "Konfederacja", "PSL", "Other")
      )
  )

point_dta <-
  polls[names(polls) %in% c("midDate", "PiS", "KO", "Lewica", "Konfederacja", "Other", "PSL", "Polska2050")] %>%
  pivot_longer(
    cols = -midDate,
    names_to = "party",
    values_to = "est"
  ) %>%
  mutate(
    party =
      party %>%
      factor(
        levels = c("PiS", "KO", "Polska2050", "Lewica", "Konfederacja", "PSL", "Other"),
        labels = c("PiS", "KO", "Polska 2050", "Lewica", "Konfederacja", "PSL", "Other")
      )
  )

ggplot() +
  geom_point(data=point_dta, aes(x = midDate, y = est, colour = party, fill=party), alpha = .5, size = 1, show.legend=FALSE) +
  stat_lineribbon(data=pred_dta, aes(x = date, y = .value, color=party, fill=party), .width=c(0.5, 0.66, 0.95), alpha=1/4) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b") +
  coord_cartesian(xlim = c(min(polls$midDate), max(polls$midDate)),
                  ylim = c(0, .5)) +
  scale_color_manual(values=cols) +
  scale_fill_manual(values=cols, guide=FALSE) +
  labs(y = "", x="", color="") +
  theme_minimal() +
  theme_ipsum_rc() +
  guides(colour = guide_legend(override.aes = list(alpha = 1, fill=NA))) +
  theme_changes
```

## Estimated share of seats  
\
Mean estimated seat share with 95% credible intervals. Sum total may not equal 460.

```{r, fig.align='center'}
ggplot(data=frame, mapping=aes(x=party, y=y, fill=party)) +
  geom_bar(stat="identity", width=.75, show.legend = F) +
  geom_abline(intercept=231, slope=0, colour="gray10", linetype=3) +
  geom_abline(intercept=276, slope=0, colour="gray10", linetype=3) +
  geom_abline(intercept=307, slope=0, colour="gray10", linetype=3) +
  scale_y_continuous('Number of seats', limits=c(0,320), breaks=c(0, 50, 100, 150, 200, 231, 276, 307)) +
  scale_fill_manual(name="Party", values = cols)+
  geom_label(aes(x=2, y=231), label="Legislative majority", size=3, adj=c(0), label.size=NA, fill="grey95", family="Roboto Condensed Light") +
  geom_label(aes(x=2, y=276), label="Overturn presidential veto", size=3, adj=c(0), label.size=NA, fill="grey95", family="Roboto Condensed Light") +
  geom_label(aes(x=2, y=307), label="Constitutional majority", size=3, adj=c(0), label.size=NA, fill="grey95", family="Roboto Condensed Light") +
  annotate("text", x=frame$party, y=c(frame$y+18), label=frame$y, size=4, family="Roboto Condensed Light")+
  annotate("text", x=frame$party, y=c(frame$y+8), label=paste("(",round(frame$ymin,0), "\u2013",round(frame$ymax,0),")", sep=""), size=3, family="Roboto Condensed Light") +
  labs(x="", y="% of vote") +
  theme_minimal() +
  theme_ipsum_rc() +
  theme_changes
```

## Trends by pollster  
\
Only pollsters with more than five polls are included.

```{r, fig.align='center', fig.width=12}
tab <- table(polls$org)
polls <- polls[polls$org %in% names(tab)[tab >= 5], ]

names <- data.frame(as.factor(get_labels(polls$org)))
names <- separate(names, as.factor.get_labels.polls.org.., c("house", "method"), sep="_")
names$house <- as.factor(names$house)
housenames <- fct_recode(names$house, "Kantar" = "Kantar") %>%
  fct_collapse(., Kantar=c("Kantar"))
orgnames <- glue_collapse(get_labels(housenames), ", ", last = " and ")
polls$org <- str_replace_all(polls$org, "_", ", ")

today <- interval(min(polls$midDate), Sys.Date())/years(1)

pred_dta <-
  tibble(
    time = seq(0, today, length.out = nrow(polls)),
    date = as.Date(time*365, origin = min(polls$midDate)),
    org = polls$org,
    pollster = polls$pollster
  )

pred_dta <-
  add_fitted_draws(
    model = m1,
    newdata = pred_dta
  ) %>%
  group_by(date, .category, org) %>%
  rename(party = .category) %>%
  mutate(
    party =
      party %>%
      factor(
        levels = c("PiS", "KO", "Polska2050", "Lewica", "Konfederacja", "PSL", "Other"),
        labels = c("PiS", "KO", "Polska 2050", "Lewica", "Konfederacja", "PSL", "Other")
  )
  )

point_dta <- polls %>%
  select(org, midDate, PiS, KO, Lewica, Konfederacja, Other, PSL, Polska2050) %>%
  pivot_longer(
    cols = c(-midDate, -org),
    names_to = "party",
    values_to = "est"
  ) %>%
  mutate(
    party =
      party %>%
      factor(
        levels = c("PiS", "KO", "Polska2050", "Lewica", "Konfederacja", "PSL", "Other"),
        labels = c("PiS", "KO", "Polska 2050", "Lewica", "Konfederacja", "PSL", "Other")
      )
  )

ggplot() +
  geom_point(data=point_dta, aes(x = midDate, y = est, colour=party, fill=party), alpha = .5, size = 1, show.legend=FALSE) +
  stat_lineribbon(data=pred_dta, aes(x = date, y = .value, color=party, fill=party), .width=c(0.5, 0.66, 0.95), alpha=1/4) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "1 month",
               date_labels = "%b") +
  facet_wrap(~org, nrow=3) +
  coord_cartesian(xlim = c(min(polls$midDate), max(polls$midDate)),
                  ylim = c(0, .5)) +
  scale_color_manual(values=cols) +
  scale_fill_manual(values=cols, guide=FALSE) +
  labs(y = "% of vote", x="", color="") +
  theme_minimal() +
  theme_ipsum_rc() +
  guides(colour = guide_legend(override.aes = list(alpha = 1, fill=NA))) +
  theme_changes
```
